MVCNewWifi/Controllers/AnotherController.cs
using Newtonsoft.Json;
using PagedList;
using ServiceStack;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Runtime.Caching;
using System.Threading.Tasks;
using System.Web.Mvc;
using MVCNewWifi.Models;
using MVCNewWifi.ViewModels;

namespace MVCNewWifi.Controllers
{
    public class AnotherController : Controller
    {
        const string TargetUri= "http://data.ntpc.gov.tw/NTPC/od/data/api/IMC123/?$format=json";
        const string CacheName = "WIFI_HOTSPOT";

        private const int PageSize = 10;

        private Task<List<string>> Districts
        {
            get { return this.GetDistricts(); }
        }

        private Task<List<string>> HotSpotTypes
        {
            get { return this.GetHotSpotTypes(); }
        }

        private Task<List<string>> Companys
        {
            get { return this.GetCompanys(); }
        }

        public async Task<ActionResult> Index(int page = 1)
        {
            int pageIndex = page < 1 ? 1 : page;

            var source = await this.GetHotSpotData();
            source = source.AsQueryable().OrderBy(x => x.ID);

            var model = new HotSpotViewModel
            {
                SearchParameter = new HotSpotSearchModel(),
                PageIndex = pageIndex,
                Districts = this.GetSelectList(await this.Districts, ""),
                HotSpotTypes = this.GetSelectList(await this.HotSpotTypes, ""),
                Companys = this.GetSelectList(await this.Companys, ""),
                HotSpots = source.ToPagedList(pageIndex, PageSize)
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(HotSpotViewModel model)
        {
            int pageIndex = model.PageIndex < 1 ? 1 : model.PageIndex;

            var source = await this.GetHotSpotData();
            source = source.AsQueryable();

            if (!string.IsNullOrWhiteSpace(model.SearchParameter.District))
            {
                source = source.Where(x => x.District == model.SearchParameter.District);
            }
            if (!string.IsNullOrWhiteSpace(model.SearchParameter.HotSpotType))
            {
                source = source.Where(x => x.Type == model.SearchParameter.HotSpotType);
            }
            if (!string.IsNullOrWhiteSpace(model.SearchParameter.Company))
            {
                source = source.Where(x => x.Company == model.SearchParameter.Company);
            }

            source = source.OrderBy(x => x.ID);

            var result = new HotSpotViewModel
            {
                SearchParameter = model.SearchParameter,
                PageIndex = pageIndex,
                Districts = this.GetSelectList(
                    await this.Districts,
                    model.SearchParameter.District),
                HotSpotTypes = this.GetSelectList(
                    await this.HotSpotTypes,
                    model.SearchParameter.HotSpotType),
                Companys = this.GetSelectList(
                    await this.Companys,
                    model.SearchParameter.Company),
                HotSpots = source.ToPagedList(pageIndex, PageSize)
            };

            return View(result);
        }


        /// <summary>
        /// Gets the hot spot data.
        /// </summary>
        /// <returns></returns>
        private async Task<IEnumerable<HotSpot>> GetHotSpotData()
        {
            ObjectCache cache = MemoryCache.Default;

            if (cache.Contains(CacheName))
            {
                var cacheContents = cache.GetCacheItem(CacheName);
                return cacheContents.Value as IEnumerable<HotSpot>;
            }
            else
            {
                return await RetriveHotSpotData(CacheName);
            }
        }

        /// <summary>
        /// Retrives the hot spot data.
        /// </summary>
        /// <param name="cacheName">Name of the cache.</param>
        /// <returns></returns>
        private async Task<IEnumerable<HotSpot>> RetriveHotSpotData(string cacheName)
        {
            var client = new HttpClient
            {
                MaxResponseContentBufferSize = Int32.MaxValue
            };

            var response = await client.GetStringAsync(TargetUri);

            //=====================================================================================

            var sw = new Stopwatch();
            sw.Start();

            //使用 JSON.Net
            //var collection =
            //    JsonConvert.DeserializeObject<IEnumerable<HotSpot>>(response);

            //使用 ServiceStack.Text (速度比 JSON.Net 快)
            var collection = response.FromJson<IEnumerable<HotSpot>>();

            sw.Stop();
            var ts = sw.Elapsed;

            var elapsedTime = String.Format("{0:00}h : {1:00}m :{2:00}s .{3:000}ms",
                ts.Hours, ts.Minutes, ts.Seconds,
                ts.Milliseconds / 10);
            Debug.WriteLine("RunTime: " + elapsedTime);

            //=====================================================================================

            //資料快取
            ObjectCache cacheItem = MemoryCache.Default;

            var policy = new CacheItemPolicy
            {
                AbsoluteExpiration = DateTime.Now.AddMinutes(30)
            };

            cacheItem.Add(cacheName, collection, policy);

            return collection;
        }

        /// <summary>
        /// 取得區域資料.
        /// </summary>
        /// <returns></returns>
        private async Task<List<string>> GetDistricts()
        {
            var source = await this.GetHotSpotData();
            if (source == null) return new List<string>();

            var districts = source.OrderBy(x => x.District)
                                  .Select(x => x.District)
                                  .Distinct();

            return districts.ToList();
        }

        /// <summary>
        /// 取得熱點分類.
        /// </summary>
        /// <returns></returns>
        private async Task<List<string>> GetHotSpotTypes()
        {
            var source = await this.GetHotSpotData();
            if (source == null) return new List<string>();

            var types = source.OrderBy(x => x.Type)
                              .Select(x => x.Type)
                              .Distinct();

            return types.ToList();
        }

        /// <summary>
        /// 取得業者資料.
        /// </summary>
        /// <returns></returns>
        private async Task<List<string>> GetCompanys()
        {
            var source = await this.GetHotSpotData();
            if (source == null) return new List<string>();

            var companys = source.OrderBy(x => x.Company)
                                 .Select(x => x.Company)
                                 .Distinct();

            return companys.ToList();
        }

        /// <summary>
        /// Gets the select list.
        /// </summary>
        /// <param name="source">The source.</param>
        /// <param name="selectedItem">The selected item.</param>
        /// <returns></returns>
        private List<SelectListItem> GetSelectList(
            IEnumerable<string> source,
            string selectedItem)
        {
            var selectList = source.Select(item => new SelectListItem()
            {
                Text = item,
                Value = item,
                Selected = !string.IsNullOrWhiteSpace(selectedItem)
                           &&
                           item.Equals(selectedItem, StringComparison.OrdinalIgnoreCase)
            });
            return selectList.ToList();
        }

    }
}

MVCNewWifi/Views/Another/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model MVCNewWifi.ViewModels.HotSpotViewModel

@{
    ViewBag.Title = "Another - Form.Post";
}

<div class="row">
    <h2>
        新北市 WIFI 熱點 (Form.Post)
        <small>
            資料來源：
            <a href="http://data.ntpc.gov.tw/NTPC/" target="_blank">
                新北市政府資料開放平台
            </a>
            -
            <a href="http://data.ntpc.gov.tw/NTPC/od/query?_m=detail&oid=04958686-1B92-4B74-889D-9F34409B272B" target="_blank">
                新北市WIFI熱點
            </a>
        </small>
    </h2>
</div>
<hr />
<div class="row well">
    @using (Html.BeginForm("Index", "Another", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "HotSpotList" }))
    {
        <div class="col-lg-3">
            <div class="input-group">
                <span class="input-group-addon">區域</span>
                @Html.DropDownListFor(x => x.SearchParameter.District, Model.Districts, "全部", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-3">
            <div class="input-group">
                <span class="input-group-addon">熱點分類</span>
                @Html.DropDownListFor(x => x.SearchParameter.HotSpotType, Model.HotSpotTypes, "全部", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-4">
            <div class="input-group">
                <span class="input-group-addon">業者</span>
                @Html.DropDownListFor(x => x.SearchParameter.Company, Model.Companys, "全部", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-2">
            <button type="submit" id="ButtonSubmit" class="btn btn-primary">
                <span class="glyphicon glyphicon-search"></span> 查詢
            </button>
        </div>
    }
</div>

@Html.PagedListPager(
        Model.HotSpots,
        page => Url.Action("Index", new { page = page }),
        PagedListRenderOptions.ClassicPlusFirstAndLast)

<table class="table table-striped table-hover">
    <thead>
        <tr style="background-color: #d3efff;">
            <th>
                @Html.DisplayNameFor(model => model.HotSpots.FirstOrDefault().Spot_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotSpots.FirstOrDefault().Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotSpots.FirstOrDefault().Company)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotSpots.FirstOrDefault().District)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotSpots.FirstOrDefault().Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotSpots.FirstOrDefault().Apparatus_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotSpots.FirstOrDefault().Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HotSpots.FirstOrDefault().Longitude)
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.HotSpots)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Spot_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.District)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apparatus_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Latitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Longitude)
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{
    <script type="text/javascript">
        $(function () {
            $('.pagination>li>a[href]').each(function (i, item) {
                var page = $(item).attr('href').replace('/Another?page=', '');
                $(item).attr('href', '#').click(function () { postPage(page); });
            });
        });
        function postPage(page) {
            var targetFormId = '#HotSpotList';
            if ($(targetFormId).size() > 0) {
                $('<input>')
                    .attr({ type: 'hidden', id: 'PageIndex', name: 'PageIndex', value: page })
                    .appendTo($(targetFormId));
                $(targetFormId).submit();
            }
        };
    </script>
}